-- phpMyAdmin SQL Dump
-- version 5.2.2
-- https://www.phpmyadmin.net/
--
-- Servidor: database:3306
-- Tiempo de generación: 20-11-2025 a las 11:02:51
-- Versión del servidor: 8.4.6
-- Versión de PHP: 8.2.29

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

--
-- Base de datos: `persutildb`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `blog`
--

CREATE TABLE `blog` (
  `id` bigint NOT NULL,
  `titulo` varchar(1024) CHARACTER SET utf32 COLLATE utf32_unicode_ci NOT NULL,
  `contenido` longtext CHARACTER SET utf32 COLLATE utf32_unicode_ci NOT NULL,
  `etiquetas` varchar(1024) CHARACTER SET utf32 COLLATE utf32_unicode_ci NOT NULL,
  `fecha_creacion` datetime NOT NULL,
  `fecha_modificacion` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf32 COLLATE=utf32_unicode_ci;

--
-- Volcado de datos para la tabla `blog`
--

INSERT INTO `blog` (`id`, `titulo`, `contenido`, `etiquetas`, `fecha_creacion`, `fecha_modificacion`) VALUES
(1, 'La suerte favorece a los audaces', 'El tiempo lo dirá El cambio es la única constante en la vida La comunicación es clave en cualquier relación La vida es bella La comunicación es clave en cualquier relación', 'clave, constante, única', '2025-11-18 12:27:15', NULL),
(2, 'La esperanza es lo último que se pierde', 'El que no arriesga no gana El respeto es la base de toda relación \nLa vida es bella La perseverancia es la clave del éxito Más vale tarde que nunca El respeto es la base de toda relación El respeto es la base de toda relación La suerte favorece a los audaces La unión hace la fuerza El respeto es la base de toda relación El que no arriesga no gana El respeto es la base de toda relación El tiempo es oro \nLa creatividad es la inteligencia divirtiéndose El tiempo es oro La unión hace la fuerza Más vale pájaro en mano que ciento volando La esperanza es lo último que se pierde A mal tiempo, buena cara El que no arriesga no gana El tiempo lo dirá La comunicación es clave en cualquier relación El conocimiento es poder.', 'divirtiéndose, tarde, favorece, comunicación, audaces', '2025-11-18 12:27:27', NULL),
(3, 'Más vale pájaro en mano que ciento volando', 'La vida es bella La creatividad es la inteligencia divirtiéndose La creatividad es la inteligencia divirtiéndose La perseverancia es la clave del éxito El tiempo es oro La creatividad es la inteligencia divirtiéndose El respeto es la base de toda relación A mal tiempo, buena cara La esperanza es lo último que se pierde \nEl tiempo es oro El respeto es la base de toda relación A mal tiempo, buena cara La unión hace la fuerza \nA mal tiempo, buena cara El respeto es la base de toda relación El respeto es la base de toda relación', 'esperanza, unión, divirtiéndose, clave', '2025-11-18 12:27:27', NULL),
(4, 'El tiempo es oro', 'Más vale pájaro en mano que ciento volando El conocimiento es poder. El que no arriesga no gana A mal tiempo, buena cara Más vale tarde que nunca La perseverancia es la clave del éxito La vida es bella Más vale pájaro en mano que ciento volando Más vale tarde que nunca El tiempo es oro La perseverancia es la clave del éxito La comunicación es clave en cualquier relación Más vale tarde que nunca A mal tiempo, buena cara La perseverancia es la clave del éxito Más vale pájaro en mano que ciento volando La esperanza es lo último que se pierde', 'éxito, clave, esperanza, tarde', '2025-11-18 12:27:39', NULL),
(5, 'La comunicación es clave en cualquier relación', 'La esperanza es lo último que se pierde La esperanza es lo último que se pierde El cambio es la única constante en la vida La vida es bella El cambio es la única constante en la vida', 'esperanza, bella, constante', '2025-11-18 12:27:39', NULL),
(6, 'Más vale pájaro en mano que ciento volando', 'A mal tiempo, buena cara La creatividad es la inteligencia divirtiéndose La perseverancia es la clave del éxito El que no arriesga no gana La perseverancia es la clave del éxito Más vale pájaro en mano que ciento volando La suerte favorece a los audaces A mal tiempo, buena cara La comunicación es clave en cualquier relación La vida es bella Más vale tarde que nunca La unión hace la fuerza El que no arriesga no gana La unión hace la fuerza La vida es bella \nMás vale pájaro en mano que ciento volando La esperanza es lo último que se pierde El conocimiento es poder. La unión hace la fuerza A mal tiempo, buena cara La unión hace la fuerza \nMás vale pájaro en mano que ciento volando La unión hace la fuerza La esperanza es lo último que se pierde La creatividad es la inteligencia divirtiéndose El conocimiento es poder. A mal tiempo, buena cara', 'ciento, esperanza, cualquier, perseverancia', '2025-11-18 12:27:39', NULL),
(7, 'El respeto es la base de toda relación', 'La comunicación es clave en cualquier relación El tiempo lo dirá La unión hace la fuerza La unión hace la fuerza El que no arriesga no gana La esperanza es lo último que se pierde La creatividad es la inteligencia divirtiéndose La comunicación es clave en cualquier relación La creatividad es la inteligencia divirtiéndose Más vale tarde que nunca La unión hace la fuerza El tiempo es oro Más vale pájaro en mano que ciento volando \nA mal tiempo, buena cara \nLa unión hace la fuerza El respeto es la base de toda relación Más vale tarde que nunca \nLa esperanza es lo último que se pierde La comunicación es clave en cualquier relación \nLa suerte favorece a los audaces La unión hace la fuerza El tiempo lo dirá \nEl que no arriesga no gana A mal tiempo, buena cara A mal tiempo, buena cara', 'pierde, divirtiéndose, pájaro, arriesga, clave', '2025-11-18 12:27:39', NULL),
(8, 'El tiempo es oro', 'La comunicación es clave en cualquier relación', 'clave, comunicación, relación', '2025-11-18 12:27:39', NULL),
(9, 'Más vale pájaro en mano que ciento volando', 'La suerte favorece a los audaces \nLa comunicación es clave en cualquier relación Más vale pájaro en mano que ciento volando El respeto es la base de toda relación \nLa comunicación es clave en cualquier relación La vida es bella El tiempo lo dirá La comunicación es clave en cualquier relación La esperanza es lo último que se pierde Más vale pájaro en mano que ciento volando \nEl conocimiento es poder. Más vale tarde que nunca La suerte favorece a los audaces Más vale pájaro en mano que ciento volando El cambio es la única constante en la vida El cambio es la única constante en la vida La suerte favorece a los audaces La vida es bella El tiempo lo dirá A mal tiempo, buena cara Más vale tarde que nunca El tiempo lo dirá La creatividad es la inteligencia divirtiéndose La comunicación es clave en cualquier relación La creatividad es la inteligencia divirtiéndose La esperanza es lo último que se pierde', 'clave, cualquier, favorece, creatividad, inteligencia', '2025-11-18 12:27:39', NULL),
(10, 'La vida es bella', 'Más vale tarde que nunca La suerte favorece a los audaces A mal tiempo, buena cara La suerte favorece a los audaces La comunicación es clave en cualquier relación El tiempo lo dirá La vida es bella El cambio es la única constante en la vida La suerte favorece a los audaces El que no arriesga no gana El tiempo es oro La comunicación es clave en cualquier relación La unión hace la fuerza La vida es bella', 'comunicación, única, relación, unión', '2025-11-18 12:27:39', NULL),
(11, 'El respeto es la base de toda relación', 'La esperanza es lo último que se pierde La vida es bella La esperanza es lo último que se pierde La comunicación es clave en cualquier relación La esperanza es lo último que se pierde Más vale pájaro en mano que ciento volando', 'pierde, comunicación, cualquier, esperanza', '2025-11-18 12:27:50', NULL),
(12, 'La suerte favorece a los audaces', 'El que no arriesga no gana A mal tiempo, buena cara El conocimiento es poder.', 'poder, buena, conocimiento, tiempo', '2025-11-18 12:27:50', NULL),
(13, 'El tiempo es oro', 'El tiempo lo dirá El tiempo es oro La suerte favorece a los audaces El tiempo lo dirá La perseverancia es la clave del éxito La creatividad es la inteligencia divirtiéndose Más vale tarde que nunca La perseverancia es la clave del éxito El tiempo lo dirá A mal tiempo, buena cara El tiempo es oro El cambio es la única constante en la vida La creatividad es la inteligencia divirtiéndose La perseverancia es la clave del éxito Más vale tarde que nunca El que no arriesga no gana La comunicación es clave en cualquier relación El tiempo lo dirá Más vale tarde que nunca Más vale pájaro en mano que ciento volando A mal tiempo, buena cara Más vale pájaro en mano que ciento volando El que no arriesga no gana \nLa comunicación es clave en cualquier relación La vida es bella La vida es bella La perseverancia es la clave del éxito La suerte favorece a los audaces Más vale tarde que nunca La unión hace la fuerza', 'unión, arriesga, nunca, relación, creatividad', '2025-11-18 12:27:50', NULL),
(14, 'El conocimiento es poder.', 'La creatividad es la inteligencia divirtiéndose El cambio es la única constante en la vida La perseverancia es la clave del éxito El conocimiento es poder. El respeto es la base de toda relación La vida es bella La perseverancia es la clave del éxito La perseverancia es la clave del éxito \nLa perseverancia es la clave del éxito La unión hace la fuerza La perseverancia es la clave del éxito Más vale pájaro en mano que ciento volando El tiempo es oro La perseverancia es la clave del éxito A mal tiempo, buena cara El cambio es la única constante en la vida El conocimiento es poder. Más vale pájaro en mano que ciento volando \nLa suerte favorece a los audaces El respeto es la base de toda relación \nLa creatividad es la inteligencia divirtiéndose La suerte favorece a los audaces', 'relación, constante, unión, audaces', '2025-11-18 12:27:50', NULL),
(15, 'A mal tiempo, buena cara', 'El respeto es la base de toda relación La vida es bella Más vale tarde que nunca La perseverancia es la clave del éxito El cambio es la única constante en la vida La perseverancia es la clave del éxito Más vale pájaro en mano que ciento volando \nEl que no arriesga no gana El que no arriesga no gana El tiempo lo dirá La suerte favorece a los audaces El tiempo lo dirá Más vale tarde que nunca El tiempo lo dirá Más vale tarde que nunca A mal tiempo, buena cara La creatividad es la inteligencia divirtiéndose Más vale pájaro en mano que ciento volando El conocimiento es poder. La vida es bella Más vale pájaro en mano que ciento volando La comunicación es clave en cualquier relación La suerte favorece a los audaces \nLa comunicación es clave en cualquier relación Más vale pájaro en mano que ciento volando El tiempo es oro La creatividad es la inteligencia divirtiéndose', 'bella, perseverancia, inteligencia, favorece', '2025-11-18 12:27:50', NULL),
(16, 'La comunicación es clave en cualquier relación', 'La unión hace la fuerza El cambio es la única constante en la vida La perseverancia es la clave del éxito La creatividad es la inteligencia divirtiéndose El que no arriesga no gana La suerte favorece a los audaces La suerte favorece a los audaces El tiempo es oro La creatividad es la inteligencia divirtiéndose Más vale pájaro en mano que ciento volando La vida es bella Más vale tarde que nunca El conocimiento es poder.', 'pájaro, tiempo, fuerza, constante', '2025-11-18 12:27:50', NULL),
(17, 'El tiempo es oro', 'El conocimiento es poder. \nEl conocimiento es poder. El cambio es la única constante en la vida El respeto es la base de toda relación El tiempo lo dirá A mal tiempo, buena cara Más vale pájaro en mano que ciento volando \nLa comunicación es clave en cualquier relación La unión hace la fuerza La comunicación es clave en cualquier relación El respeto es la base de toda relación El que no arriesga no gana La comunicación es clave en cualquier relación La esperanza es lo último que se pierde Más vale pájaro en mano que ciento volando \nLa esperanza es lo último que se pierde La comunicación es clave en cualquier relación El que no arriesga no gana El tiempo es oro El conocimiento es poder. \nLa suerte favorece a los audaces Más vale pájaro en mano que ciento volando El conocimiento es poder. La comunicación es clave en cualquier relación \nLa creatividad es la inteligencia divirtiéndose La comunicación es clave en cualquier relación', 'cualquier, inteligencia, pájaro, unión, volando', '2025-11-18 12:27:50', NULL),
(18, 'El que no arriesga no gana', 'El tiempo lo dirá La vida es bella La esperanza es lo último que se pierde La esperanza es lo último que se pierde El que no arriesga no gana La unión hace la fuerza La esperanza es lo último que se pierde El que no arriesga no gana El conocimiento es poder. El tiempo es oro La comunicación es clave en cualquier relación El tiempo lo dirá \nEl cambio es la única constante en la vida La perseverancia es la clave del éxito \nEl respeto es la base de toda relación La creatividad es la inteligencia divirtiéndose La creatividad es la inteligencia divirtiéndose El que no arriesga no gana La esperanza es lo último que se pierde \nEl que no arriesga no gana La comunicación es clave en cualquier relación El que no arriesga no gana El cambio es la única constante en la vida El respeto es la base de toda relación La unión hace la fuerza A mal tiempo, buena cara El respeto es la base de toda relación La unión hace la fuerza El cambio es la única constante en la vida El que no arriesga no gana', 'clave, respeto, creatividad, bella', '2025-11-18 12:27:50', NULL),
(19, 'La perseverancia es la clave del éxito', 'El tiempo es oro', 'tiempo', '2025-11-18 12:27:50', NULL),
(20, 'La comunicación es clave en cualquier relación', 'La vida es bella El tiempo es oro El conocimiento es poder. A mal tiempo, buena cara La comunicación es clave en cualquier relación La unión hace la fuerza La comunicación es clave en cualquier relación La creatividad es la inteligencia divirtiéndose Más vale tarde que nunca El tiempo lo dirá La perseverancia es la clave del éxito El que no arriesga no gana El que no arriesga no gana El que no arriesga no gana La unión hace la fuerza La perseverancia es la clave del éxito La esperanza es lo último que se pierde La suerte favorece a los audaces Más vale pájaro en mano que ciento volando El conocimiento es poder. La comunicación es clave en cualquier relación La comunicación es clave en cualquier relación', 'audaces, esperanza, relación', '2025-11-18 12:27:50', NULL),
(21, 'La esperanza es lo último que se pierde', 'El respeto es la base de toda relación El que no arriesga no gana \nLa unión hace la fuerza \nEl respeto es la base de toda relación \nEl respeto es la base de toda relación La esperanza es lo último que se pierde La creatividad es la inteligencia divirtiéndose La esperanza es lo último que se pierde La comunicación es clave en cualquier relación La suerte favorece a los audaces El respeto es la base de toda relación La comunicación es clave en cualquier relación A mal tiempo, buena cara La vida es bella La vida es bella La perseverancia es la clave del éxito Más vale tarde que nunca El conocimiento es poder. La vida es bella La esperanza es lo último que se pierde El conocimiento es poder. El que no arriesga no gana El que no arriesga no gana \nEl tiempo es oro La creatividad es la inteligencia divirtiéndose El tiempo lo dirá El conocimiento es poder. El conocimiento es poder. A mal tiempo, buena cara \nEl tiempo lo dirá', 'bella, creatividad, favorece, último', '2025-11-18 12:27:50', NULL),
(22, 'La comunicación es clave en cualquier relación', 'El tiempo lo dirá El cambio es la única constante en la vida La suerte favorece a los audaces A mal tiempo, buena cara El conocimiento es poder. El conocimiento es poder. El tiempo es oro El cambio es la única constante en la vida', 'poder, única, conocimiento, tiempo, suerte', '2025-11-18 12:27:50', NULL),
(23, 'La esperanza es lo último que se pierde', 'El respeto es la base de toda relación El respeto es la base de toda relación El tiempo lo dirá El tiempo es oro El que no arriesga no gana El tiempo lo dirá', 'tiempo, arriesga', '2025-11-18 12:27:51', NULL),
(24, 'La comunicación es clave en cualquier relación', 'La esperanza es lo último que se pierde \nEl que no arriesga no gana La comunicación es clave en cualquier relación El respeto es la base de toda relación La creatividad es la inteligencia divirtiéndose La unión hace la fuerza El respeto es la base de toda relación El tiempo lo dirá El respeto es la base de toda relación', 'unión, último, esperanza, fuerza, comunicación', '2025-11-18 12:27:51', NULL),
(25, 'A mal tiempo, buena cara', 'El que no arriesga no gana La esperanza es lo último que se pierde La vida es bella La suerte favorece a los audaces El cambio es la única constante en la vida La vida es bella El tiempo lo dirá El tiempo lo dirá La creatividad es la inteligencia divirtiéndose El que no arriesga no gana \nLa unión hace la fuerza El tiempo lo dirá \nA mal tiempo, buena cara La esperanza es lo último que se pierde La unión hace la fuerza La esperanza es lo último que se pierde Más vale tarde que nunca La vida es bella La creatividad es la inteligencia divirtiéndose El tiempo es oro La creatividad es la inteligencia divirtiéndose La comunicación es clave en cualquier relación La vida es bella El tiempo es oro Más vale tarde que nunca A mal tiempo, buena cara Más vale tarde que nunca A mal tiempo, buena cara', 'constante, pierde, unión, favorece, creatividad', '2025-11-18 12:27:51', NULL),
(26, 'El que no arriesga no gana', 'Más vale tarde que nunca La vida es bella El tiempo es oro El tiempo es oro Más vale pájaro en mano que ciento volando Más vale pájaro en mano que ciento volando La unión hace la fuerza A mal tiempo, buena cara La esperanza es lo último que se pierde La esperanza es lo último que se pierde El respeto es la base de toda relación El tiempo es oro \nEl cambio es la única constante en la vida El que no arriesga no gana \nEl cambio es la única constante en la vida A mal tiempo, buena cara Más vale tarde que nunca El tiempo lo dirá Más vale tarde que nunca \nEl cambio es la única constante en la vida La comunicación es clave en cualquier relación', 'nunca, buena, ciento, fuerza, cambio', '2025-11-18 12:27:51', NULL),
(27, 'Más vale tarde que nunca', 'El que no arriesga no gana \nLa creatividad es la inteligencia divirtiéndose El tiempo es oro La vida es bella El conocimiento es poder. Más vale pájaro en mano que ciento volando El tiempo lo dirá El cambio es la única constante en la vida El tiempo lo dirá El respeto es la base de toda relación La vida es bella El tiempo es oro \nA mal tiempo, buena cara', 'ciento, constante, volando, cambio', '2025-11-18 12:27:51', NULL),
(28, 'El que no arriesga no gana', 'La perseverancia es la clave del éxito El respeto es la base de toda relación El que no arriesga no gana El tiempo lo dirá La suerte favorece a los audaces La creatividad es la inteligencia divirtiéndose El tiempo lo dirá El que no arriesga no gana Más vale pájaro en mano que ciento volando El conocimiento es poder. Más vale pájaro en mano que ciento volando El tiempo es oro La creatividad es la inteligencia divirtiéndose La comunicación es clave en cualquier relación El cambio es la única constante en la vida El cambio es la única constante en la vida La comunicación es clave en cualquier relación La esperanza es lo último que se pierde La creatividad es la inteligencia divirtiéndose La vida es bella La comunicación es clave en cualquier relación La suerte favorece a los audaces La suerte favorece a los audaces La comunicación es clave en cualquier relación El que no arriesga no gana La suerte favorece a los audaces La esperanza es lo último que se pierde', 'inteligencia, pájaro, favorece, comunicación', '2025-11-18 12:27:51', NULL),
(29, 'La vida es bella', 'Más vale tarde que nunca La esperanza es lo último que se pierde La suerte favorece a los audaces La creatividad es la inteligencia divirtiéndose La perseverancia es la clave del éxito', 'perseverancia, suerte, favorece', '2025-11-18 12:27:51', NULL),
(30, 'Más vale tarde que nunca', 'Más vale pájaro en mano que ciento volando \nEl cambio es la única constante en la vida El cambio es la única constante en la vida A mal tiempo, buena cara El tiempo es oro', 'volando, pájaro, única, buena, tiempo', '2025-11-18 12:27:51', NULL),
(31, 'La perseverancia es la clave del éxito', 'El tiempo lo dirá La esperanza es lo último que se pierde Más vale tarde que nunca \nMás vale tarde que nunca La suerte favorece a los audaces La suerte favorece a los audaces A mal tiempo, buena cara La esperanza es lo último que se pierde Más vale tarde que nunca La vida es bella Más vale tarde que nunca \nA mal tiempo, buena cara A mal tiempo, buena cara La unión hace la fuerza \nMás vale pájaro en mano que ciento volando La unión hace la fuerza La creatividad es la inteligencia divirtiéndose \nLa unión hace la fuerza A mal tiempo, buena cara La esperanza es lo último que se pierde El conocimiento es poder.', 'ciento, último, tarde, fuerza, divirtiéndose', '2025-11-18 12:27:51', NULL),
(32, 'La suerte favorece a los audaces', 'El cambio es la única constante en la vida La vida es bella El que no arriesga no gana La vida es bella Más vale pájaro en mano que ciento volando La esperanza es lo último que se pierde La comunicación es clave en cualquier relación El conocimiento es poder. El que no arriesga no gana El conocimiento es poder. La vida es bella \nEl tiempo lo dirá El cambio es la única constante en la vida Más vale tarde que nunca Más vale pájaro en mano que ciento volando Más vale pájaro en mano que ciento volando El que no arriesga no gana A mal tiempo, buena cara Más vale tarde que nunca La creatividad es la inteligencia divirtiéndose La esperanza es lo último que se pierde Más vale pájaro en mano que ciento volando La esperanza es lo último que se pierde El tiempo es oro Más vale tarde que nunca \nLa suerte favorece a los audaces', 'inteligencia, cualquier, último, pájaro, buena', '2025-11-18 12:27:51', NULL),
(33, 'La vida es bella', 'Más vale pájaro en mano que ciento volando A mal tiempo, buena cara A mal tiempo, buena cara El respeto es la base de toda relación Más vale pájaro en mano que ciento volando A mal tiempo, buena cara La esperanza es lo último que se pierde La perseverancia es la clave del éxito La perseverancia es la clave del éxito \nLa esperanza es lo último que se pierde La suerte favorece a los audaces El respeto es la base de toda relación La comunicación es clave en cualquier relación La vida es bella \nMás vale pájaro en mano que ciento volando El cambio es la única constante en la vida A mal tiempo, buena cara El cambio es la única constante en la vida Más vale pájaro en mano que ciento volando La creatividad es la inteligencia divirtiéndose \nEl que no arriesga no gana A mal tiempo, buena cara La vida es bella La unión hace la fuerza La vida es bella El tiempo lo dirá El respeto es la base de toda relación La vida es bella', 'arriesga, tiempo, divirtiéndose, pierde, fuerza', '2025-11-18 12:27:51', NULL),
(34, 'El tiempo lo dirá', 'La suerte favorece a los audaces El cambio es la única constante en la vida La unión hace la fuerza La comunicación es clave en cualquier relación A mal tiempo, buena cara El tiempo lo dirá El conocimiento es poder. La suerte favorece a los audaces La comunicación es clave en cualquier relación La esperanza es lo último que se pierde Más vale tarde que nunca El tiempo es oro La creatividad es la inteligencia divirtiéndose Más vale pájaro en mano que ciento volando Más vale pájaro en mano que ciento volando La suerte favorece a los audaces La unión hace la fuerza La comunicación es clave en cualquier relación Más vale pájaro en mano que ciento volando El tiempo lo dirá El que no arriesga no gana La esperanza es lo último que se pierde \nLa esperanza es lo último que se pierde La esperanza es lo último que se pierde La suerte favorece a los audaces', 'último, tiempo, cualquier, fuerza', '2025-11-18 12:27:51', NULL),
(35, 'Más vale tarde que nunca', 'Más vale tarde que nunca El tiempo lo dirá Más vale tarde que nunca El que no arriesga no gana El tiempo es oro El respeto es la base de toda relación Más vale tarde que nunca La unión hace la fuerza \nEl que no arriesga no gana A mal tiempo, buena cara El tiempo lo dirá La suerte favorece a los audaces La esperanza es lo último que se pierde El respeto es la base de toda relación La suerte favorece a los audaces La creatividad es la inteligencia divirtiéndose El tiempo es oro La esperanza es lo último que se pierde El conocimiento es poder. El cambio es la única constante en la vida El tiempo es oro El tiempo lo dirá', 'constante, única, tarde, conocimiento', '2025-11-18 12:27:51', NULL),
(36, 'La suerte favorece a los audaces', 'La unión hace la fuerza La esperanza es lo último que se pierde Más vale pájaro en mano que ciento volando \nLa vida es bella El respeto es la base de toda relación El tiempo es oro El cambio es la única constante en la vida La vida es bella \nLa creatividad es la inteligencia divirtiéndose El cambio es la única constante en la vida La suerte favorece a los audaces Más vale pájaro en mano que ciento volando A mal tiempo, buena cara El cambio es la única constante en la vida A mal tiempo, buena cara El respeto es la base de toda relación La creatividad es la inteligencia divirtiéndose Más vale pájaro en mano que ciento volando', 'último, cambio, única, ciento', '2025-11-18 12:27:51', NULL),
(37, 'El respeto es la base de toda relación', 'La comunicación es clave en cualquier relación La vida es bella La creatividad es la inteligencia divirtiéndose Más vale pájaro en mano que ciento volando La perseverancia es la clave del éxito \nLa creatividad es la inteligencia divirtiéndose La esperanza es lo último que se pierde El cambio es la única constante en la vida El tiempo lo dirá \nMás vale tarde que nunca Más vale tarde que nunca A mal tiempo, buena cara El respeto es la base de toda relación Más vale tarde que nunca Más vale pájaro en mano que ciento volando \nEl respeto es la base de toda relación La suerte favorece a los audaces \nMás vale pájaro en mano que ciento volando Más vale tarde que nunca El tiempo lo dirá La vida es bella', 'relación, ciento, favorece, única', '2025-11-18 12:27:51', NULL),
(38, 'La suerte favorece a los audaces', 'El que no arriesga no gana El conocimiento es poder. La unión hace la fuerza Más vale tarde que nunca El cambio es la única constante en la vida El cambio es la única constante en la vida El cambio es la única constante en la vida La perseverancia es la clave del éxito El respeto es la base de toda relación Más vale tarde que nunca La perseverancia es la clave del éxito El respeto es la base de toda relación \nLa comunicación es clave en cualquier relación La comunicación es clave en cualquier relación \nMás vale tarde que nunca El tiempo es oro El que no arriesga no gana Más vale tarde que nunca Más vale pájaro en mano que ciento volando El cambio es la única constante en la vida La perseverancia es la clave del éxito La vida es bella El que no arriesga no gana El que no arriesga no gana El tiempo lo dirá La vida es bella La perseverancia es la clave del éxito', 'única, constante, comunicación, tiempo, cualquier', '2025-11-18 12:27:51', NULL),
(39, 'Más vale tarde que nunca', 'Más vale tarde que nunca El cambio es la única constante en la vida La comunicación es clave en cualquier relación El que no arriesga no gana La unión hace la fuerza El respeto es la base de toda relación', 'nunca, constante, arriesga, fuerza, cambio', '2025-11-18 12:27:52', NULL),
(40, 'El tiempo lo dirá', 'La perseverancia es la clave del éxito El que no arriesga no gana El tiempo lo dirá La perseverancia es la clave del éxito El tiempo lo dirá La unión hace la fuerza La unión hace la fuerza El cambio es la única constante en la vida La comunicación es clave en cualquier relación El que no arriesga no gana \nMás vale tarde que nunca \nEl tiempo lo dirá \nLa unión hace la fuerza Más vale pájaro en mano que ciento volando La creatividad es la inteligencia divirtiéndose Más vale pájaro en mano que ciento volando El tiempo lo dirá Más vale pájaro en mano que ciento volando', 'volando, divirtiéndose, tarde, cambio', '2025-11-18 12:27:52', NULL),
(41, 'La perseverancia es la clave del éxito', 'El conocimiento es poder. La creatividad es la inteligencia divirtiéndose A mal tiempo, buena cara El respeto es la base de toda relación La perseverancia es la clave del éxito El tiempo lo dirá La suerte favorece a los audaces La suerte favorece a los audaces La vida es bella El conocimiento es poder. La perseverancia es la clave del éxito El que no arriesga no gana', 'conocimiento, buena, creatividad, suerte, inteligencia', '2025-11-18 12:27:52', NULL),
(42, 'A mal tiempo, buena cara', 'El respeto es la base de toda relación El respeto es la base de toda relación La vida es bella A mal tiempo, buena cara La unión hace la fuerza La creatividad es la inteligencia divirtiéndose La unión hace la fuerza El tiempo es oro', 'tiempo, fuerza, divirtiéndose', '2025-11-18 12:27:52', NULL),
(43, 'El tiempo lo dirá', 'La vida es bella Más vale tarde que nunca El respeto es la base de toda relación La perseverancia es la clave del éxito', 'respeto, nunca, relación, clave', '2025-11-18 12:27:52', NULL),
(44, 'La creatividad es la inteligencia divirtiéndose', 'La vida es bella \nLa vida es bella El que no arriesga no gana La vida es bella La suerte favorece a los audaces El tiempo es oro El respeto es la base de toda relación El tiempo es oro La perseverancia es la clave del éxito El tiempo lo dirá La vida es bella \nLa perseverancia es la clave del éxito \nEl respeto es la base de toda relación El tiempo es oro La creatividad es la inteligencia divirtiéndose Más vale pájaro en mano que ciento volando La unión hace la fuerza El cambio es la única constante en la vida La vida es bella El conocimiento es poder. La comunicación es clave en cualquier relación \nLa unión hace la fuerza Más vale tarde que nunca El cambio es la única constante en la vida El conocimiento es poder. La unión hace la fuerza La vida es bella La esperanza es lo último que se pierde El tiempo lo dirá La esperanza es lo último que se pierde', 'clave, pierde, perseverancia, inteligencia', '2025-11-18 12:27:52', NULL),
(45, 'El conocimiento es poder.', 'La comunicación es clave en cualquier relación La vida es bella El respeto es la base de toda relación Más vale tarde que nunca El conocimiento es poder. El tiempo es oro El que no arriesga no gana La creatividad es la inteligencia divirtiéndose La creatividad es la inteligencia divirtiéndose La esperanza es lo último que se pierde Más vale pájaro en mano que ciento volando La esperanza es lo último que se pierde El cambio es la única constante en la vida Más vale tarde que nunca', 'inteligencia, poder, conocimiento, bella', '2025-11-18 12:27:52', NULL),
(46, 'La creatividad es la inteligencia divirtiéndose', 'La comunicación es clave en cualquier relación \nEl que no arriesga no gana La suerte favorece a los audaces El cambio es la única constante en la vida El cambio es la única constante en la vida La perseverancia es la clave del éxito El respeto es la base de toda relación La unión hace la fuerza La perseverancia es la clave del éxito El que no arriesga no gana La vida es bella Más vale tarde que nunca Más vale tarde que nunca El tiempo lo dirá El que no arriesga no gana La perseverancia es la clave del éxito La suerte favorece a los audaces La comunicación es clave en cualquier relación El conocimiento es poder. \nEl respeto es la base de toda relación Más vale tarde que nunca La vida es bella La esperanza es lo último que se pierde \nLa suerte favorece a los audaces El cambio es la única constante en la vida', 'esperanza, éxito, única, nunca', '2025-11-18 12:27:52', NULL),
(47, 'La comunicación es clave en cualquier relación', 'El cambio es la única constante en la vida El conocimiento es poder. Más vale pájaro en mano que ciento volando A mal tiempo, buena cara La suerte favorece a los audaces La perseverancia es la clave del éxito', 'constante, suerte, ciento', '2025-11-18 12:27:52', NULL),
(48, 'La comunicación es clave en cualquier relación', 'El que no arriesga no gana Más vale pájaro en mano que ciento volando El tiempo lo dirá El que no arriesga no gana Más vale tarde que nunca El que no arriesga no gana La creatividad es la inteligencia divirtiéndose La comunicación es clave en cualquier relación La perseverancia es la clave del éxito \nMás vale tarde que nunca El cambio es la única constante en la vida La esperanza es lo último que se pierde La suerte favorece a los audaces El cambio es la única constante en la vida La vida es bella Más vale pájaro en mano que ciento volando El tiempo es oro El que no arriesga no gana El que no arriesga no gana La vida es bella El conocimiento es poder. \nEl conocimiento es poder.', 'comunicación, nunca, creatividad, cambio, inteligencia', '2025-11-18 12:27:52', NULL),
(49, 'El cambio es la única constante en la vida', 'El tiempo lo dirá \nLa creatividad es la inteligencia divirtiéndose El respeto es la base de toda relación El respeto es la base de toda relación A mal tiempo, buena cara \nEl cambio es la única constante en la vida El tiempo lo dirá La suerte favorece a los audaces El tiempo es oro La vida es bella A mal tiempo, buena cara La creatividad es la inteligencia divirtiéndose Más vale tarde que nunca La unión hace la fuerza El cambio es la única constante en la vida El tiempo es oro El tiempo lo dirá La unión hace la fuerza La perseverancia es la clave del éxito El tiempo lo dirá La comunicación es clave en cualquier relación El conocimiento es poder. La esperanza es lo último que se pierde La suerte favorece a los audaces', 'unión, cualquier, única, relación, éxito', '2025-11-18 12:27:52', NULL),
(50, 'La esperanza es lo último que se pierde', 'Más vale pájaro en mano que ciento volando El tiempo lo dirá Más vale tarde que nunca La comunicación es clave en cualquier relación La vida es bella La comunicación es clave en cualquier relación El que no arriesga no gana La comunicación es clave en cualquier relación El respeto es la base de toda relación Más vale tarde que nunca \nA mal tiempo, buena cara La perseverancia es la clave del éxito El cambio es la única constante en la vida A mal tiempo, buena cara El tiempo es oro El cambio es la única constante en la vida A mal tiempo, buena cara El conocimiento es poder. Más vale pájaro en mano que ciento volando La creatividad es la inteligencia divirtiéndose La vida es bella El que no arriesga no gana', 'comunicación, pájaro, inteligencia, única, bella', '2025-11-18 12:27:52', NULL);

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `zanon`
--

CREATE TABLE `zanon` (
  `id` bigint NOT NULL,
  `titulo` varchar(1024) COLLATE utf32_unicode_ci NOT NULL,
  `contenido` longtext COLLATE utf32_unicode_ci NOT NULL,
  `fecha_creacion` datetime NOT NULL,
  `fecha_modificacion` datetime DEFAULT NULL,
  `publico` tinyint(1) NOT NULL,
  `categoria` varchar(255) COLLATE utf32_unicode_ci NOT NULL,
  `duracion` int NOT NULL,
  `dificultad` enum('baja','media','alta') CHARACTER SET utf32 COLLATE utf32_unicode_ci NOT NULL,
  `imagen` varchar(255) COLLATE utf32_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf32 COLLATE=utf32_unicode_ci;

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `blog`
--
ALTER TABLE `blog`
  ADD PRIMARY KEY (`id`);

--
-- Indices de la tabla `zanon`
--
ALTER TABLE `zanon`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `blog`
--
ALTER TABLE `blog`
  MODIFY `id` bigint NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=51;

--
-- AUTO_INCREMENT de la tabla `zanon`
--
ALTER TABLE `zanon`
  MODIFY `id` bigint NOT NULL AUTO_INCREMENT;
COMMIT;
